package cc.funkemunky.anticheat.api.checks;

public enum CheckType {
    AUTOCLICKER, KILLAURA, AIM, REACH, FLY, SPEED, MOTION, STEP, MOVEMENT, INVENTORY, COMBAT, BADPACKETS, VELOCITY, WORLD, JESUS, BEHAVIORAL;
}
